import Foundation

/// Layout weight for a set of siblings: how much of the parent's area each one
/// is given when the map or the rings lay it out.
///
/// Strictly proportional sizing has one failure mode that the map and the
/// rings both share: a sibling a thousand times smaller than its neighbour
/// rounds to a sliver no pointer can land on. A folder holding a 1.08 GB
/// `usr`, a 766 KB `Developer` and a 4 KB `Info.plist` draws the last two as
/// sub-pixel specks — visible in principle, unclickable in practice.
///
/// The rule here divides the parent's area in two pools:
///
/// * `1 - pooled` follows the bytes, so the picture still reads as "what is
///   big" — this is the pool that carries the meaning.
/// * `pooled` is split *equally* between the siblings, whatever their size.
///   A sibling's guaranteed floor is therefore `pooled / n`, which is what
///   makes the small ones land on a real, clickable area.
///
/// Written out, a sibling's weight is
///
///     w = (1 - pooled) · bytes + pooled · parentTotal / n
///
/// where `n` is how many siblings share the area while carrying bytes. Children
/// reporting 0 bytes are not part of `n` and are not laid out at all: they have
/// nothing to show, and counting them would both dilute every real sibling's
/// floor and (as the first cut of this code did) let the weights sum past the
/// folder's area. Because 0-byte children contribute nothing either way, the
/// weights over the laid-out siblings then sum to exactly `parentTotal`.
///
/// ## How big the pool is
///
/// `pooled` is not a constant: it grows with the number of siblings, from
/// `pooledMin` at `pooledMinCount` up to `pooledMax` at `pooledMaxCount`, then
/// holds. A folder with few items is already readable — two or three tiles are
/// all reachable at proportional sizes — so it gives up the least area; a
/// folder crowded with siblings needs the most help, so it gives up the most.
/// The growth is eased with `t³` (ease-in-cubic), which puts it late: the pool
/// stays near `pooledMin` through the common 3-10 sibling range and only opens
/// up once a folder is genuinely busy.
///
/// ### It is a memoised table, not a per-call cubic
///
/// `pooled(siblings:)` is a **pure function of `n` alone** over a small, fixed
/// domain (`1...pooledMaxCount`), so it is computed once into
/// `pooledTable` and read back thereafter. That matters because it is called
/// per *directory* by both layouts, and a directory's sibling count is the only
/// input: there are at most 49 distinct answers in the whole application, so
/// recomputing a divide-plus-cubic for each of ~300k directories on a full-disk
/// scan is work with no information in it.
///
/// The table is generated by `pooledCubic(siblings:)` — the plain formula, kept
/// as the single definition of the curve — and `make test-mapweights` asserts
/// the table equals it entry for entry, so the memo can never drift from the
/// curve it stands for. The values are exact IEEE-754 doubles and reproducible
/// bit for bit: same input, same output, on every run and every machine.
///
/// The blend is applied at *every* level, so it nests: a folder is laid out
/// among its own siblings, and its children are laid out among theirs.
///
/// Two properties the callers rely on:
///
/// * **It is only a layout weight.** Nothing displayed — the centre label
///   under the rings, a tile's tooltip, the size column in the directory
///   list — reads it. Those keep reading `Tree.alloc`, so the map shows a
///   truer picture than it draws, and the numbers never lie to make a tile
///   clickable.
/// * **It conserves the parent's used total.** For any `pooled`, `Σ w =
///   (1 - pooled)·Σbytes + pooled·parentTotal`, and `Σbytes` is `parentTotal`
///   whenever the children account for the folder (the usual case), so the sum
///   is the folder's own total and the used/free split is untouched. A caller
///   measuring shares must pass the same `n` it counts, or the sum is wrong —
///   `make test-mapweights` pins this.
///
/// ## Cost
///
/// O(1) per directory: one clamp and one array read for the pool, then two
/// multiplies and a divide per sibling. The layouts already visit every child
/// once to read its size, so this adds a constant amount of arithmetic per node
/// and, in particular, does **not** add a pass over a directory's children —
/// which matters, because a folder can hold tens of thousands of entries and
/// the layouts deliberately stop early at the first sibling too thin to draw.
/// A formulation that needed `Σbytes` as a separate pre-pass would walk all of
/// them; the parent's own total (`Tree.alloc[dir]`) keeps the *extra* work
/// proportional to what is actually drawn.

nonisolated enum ShareWeight {

    /// Share of the parent's area held back for the equal split at the smallest
    /// sibling count. Deliberately modest: a 2-3 item folder reads fine without
    /// much help.
    static let pooledMin = 0.10

    /// Sibling count at or below which the pool sits at `pooledMin`.
    static let pooledMinCount = 2

    /// Share held back once the folder is crowded.
    static let pooledMax = 0.25

    /// Sibling count at or above which the pool sits at `pooledMax`.
    ///
    /// It is also the memo's last computed entry: every larger folder clamps to
    /// `pooledMax`, so nothing beyond this needs a value.
    static let pooledMaxCount = 50

    /// Decimal places kept in the memoised pool.
    ///
    /// The pool is a heuristic nudge, not a measured quantity: a thousandth of
    /// the parent's area is far below what a pixel can resolve, and the layouts
    /// re-quantise to whole pixels anyway. Trimming the table to 3 places makes
    /// its values legible in the source (`0.100`, `0.101`, … `0.250`) and
    /// collapses runs of near-identical entries into one answer.
    static let pooledDecimals = 3

    /// The step between adjacent table entries: 10⁻³.
    static let pooledQuantum = 0.001

    /// Round to the table's precision, deterministically.
    ///
    /// `(v × 1000).rounded() / 1000` rather than a `%` or `pow` form: the
    /// intermediate is an exact integer-valued double for every value in the
    /// curve's range, so the result is a clean multiple of 0.001 with no
    /// dependence on the rounding mode, the locale, or the platform's `pow`.
    /// Monotone, so quantising preserves the curve's non-decreasing property.
    static func quantize(_ value: Double) -> Double {
        (value * 1000).rounded() / 1000
    }

    /// The plain curve: `pooledMin` through `pooledMax`, eased with `t³`.
    ///
    /// This is the single definition of the curve's *shape*, at full double
    /// precision. `pooledTable` is its memo, quantised to `pooledQuantum`; the
    /// test asserts the table equals `quantize(pooledCubic(…))` for every `n`,
    /// so this function stays the authority and the table only a cache of it.
    ///
    /// Continuous and non-decreasing in `siblings`, and flat outside the
    /// range — no cliff at either end, so a folder gaining one entry does not
    /// jump its layout, and quantising a non-decreasing function leaves it
    /// non-decreasing.
    static func pooledCubic(siblings: Int) -> Double {
        let n = Double(siblings)
        guard n > Double(pooledMinCount) else { return pooledMin }
        guard n < Double(pooledMaxCount) else { return pooledMax }
        let t = (n - Double(pooledMinCount)) / (Double(pooledMaxCount) - Double(pooledMinCount))
        return pooledMin + (pooledMax - pooledMin) * (t * t * t)
    }

    /// `pooledCubic(siblings:)` quantised to `pooledQuantum`, for every `n` in
    /// `0...pooledMaxCount`.
    ///
    /// Built once, on first use; index `n` is the answer for `n` siblings.
    /// Index 0 is present (and equals `pooledMin`) only so the lookup needs no
    /// offset arithmetic — no caller passes 0, because `weight` floors a
    /// non-positive count to 1.
    ///
    /// The quantisation costs nothing at lookup time: it happens here, over 51
    /// values, once per process. It is deterministic for the same reason the
    /// curve is — plain IEEE-754 arithmetic on constants, independent of time,
    /// locale and hashing order — and `make test-mapweights` pins the whole
    /// table bit for bit.
    private static let pooledTable: [Double] =
        (0...pooledMaxCount).map { quantize(pooledCubic(siblings: $0)) }

    /// The pool for a folder of `siblings` sized children — a clamp and a table
    /// read. See `pooledCubic(siblings:)` for the curve this memoises.
    static func pooled(siblings: Int) -> Double {
        // Clamped *before* the lookup, so the table needs no out-of-range
        // entries and a 10,000-sibling folder reads the same value as a 50.
        if siblings <= 0 { return pooledMin }
        if siblings >= pooledMaxCount { return pooledMax }
        return pooledTable[siblings]
    }

    /// The area one sibling is guaranteed by the pool alone, as a fraction of
    /// the parent — the number that decides reachability for the small ones.
    ///
    /// A convenience for tests and reasoning: it is exactly
    /// `pooled(siblings:) / siblings`.
    static func floor(siblings: Int) -> Double {
        siblings > 0 ? pooled(siblings: siblings) / Double(siblings) : 0
    }

    /// Weight of one sibling, in bytes' units, so it can be handed straight to
    /// a layout that expects sizes.
    ///
    /// - Parameters:
    ///   - bytes: the sibling's own allocated bytes.
    ///   - siblings: how many siblings with bytes are laid out beside it,
    ///     including itself. Non-positive is treated as one, so a lone child
    ///     keeps the parent's full area.
    ///   - parentTotal: the parent's allocated bytes — the area being shared.
    ///     Zero yields a zero weight, which the callers treat as "nothing to
    ///     draw" rather than dividing by it.
    static func weight(bytes: UInt64, siblings: Int, parentTotal: UInt64) -> Double {
        let n = siblings > 0 ? Double(siblings) : 1
        let p = pooled(siblings: siblings > 0 ? siblings : 1)
        let pool = Double(parentTotal) * p / n
        return (1 - p) * Double(bytes) + pool
    }

    /// The weight as a fraction of `parentTotal`, for callers that reason in
    /// shares rather than in layout units.
    static func share(bytes: UInt64, siblings: Int, parentTotal: UInt64) -> Double {
        guard parentTotal > 0 else { return 0 }
        return weight(bytes: bytes, siblings: siblings, parentTotal: parentTotal) / Double(parentTotal)
    }
}
